runtime: custom
env: flex

#network:
#    forwarded_ports:
#        - 8080:5000

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

# [START configuration]
endpoints_api_service:
  # The following values are to be replaced by information from the output of
  # 'gcloud endpoints services deploy openapi-appengine.yaml' command.
  name: bluej-pintro-project.appspot.com 
  rollout_strategy: managed
 # [END configuration]
